gogs:
    image: docker.io/gogs/gogs:latest
    links:
      - mysql-gogs:mysql
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /opt/docker/gogs/:/data/docker/gogs
    restart: always
  
mysql-gogs:
    image: docker.io/mysql:5.7.7
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/gogs/mysql:/var/lib/mysql
      - ~/docker/gogs/conf.d:/etc/mysql/conf.d:rw
    environment:
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=gogs
      - MYSQL_ROOT_PASSWORD=123456
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always